import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#0f1c2c",
        "secondary-fixed": "#ffddb7",
        "primary-fixed-dim": "#bac8dc",
        "inverse-primary": "#bac8dc",
        "on-secondary-fixed": "#2a1700",
        "surface-bright": "#fbf9f6",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3a4859",
        "on-tertiary-fixed-variant": "#005232",
        "on-background": "#1b1c1a",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#93f7bf",
        "surface-container": "#efeeeb",
        primary: "#000000",
        "on-surface": "#1b1c1a",
        "surface-container-low": "#f5f3f0",
        "on-primary-container": "#778598",
        "tertiary-fixed-dim": "#77daa4",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fdae3c",
        "surface-variant": "#e4e2df",
        "secondary-fixed-dim": "#ffb95c",
        "on-error": "#ffffff",
        "primary-container": "#0f1c2c",
        "on-secondary-fixed-variant": "#653e00",
        surface: "#fbf9f6",
        error: "#ba1a1a",
        "outline-variant": "#c4c6cc",
        "inverse-surface": "#30312f",
        outline: "#74777d",
        background: "#fbf9f6",
        "surface-container-highest": "#e4e2df",
        "on-tertiary-fixed": "#002112",
        "on-surface-variant": "#44474c",
        "surface-container-lowest": "#ffffff",
        secondary: "#845400",
        tertiary: "#000000",
        "primary-fixed": "#d6e4f9",
        "tertiary-container": "#002112",
        "on-secondary-container": "#6d4400",
        "on-tertiary-container": "#2e9565",
        "error-container": "#ffdad6",
        "surface-tint": "#525f71",
        "surface-dim": "#dbdad7",
        "on-primary": "#ffffff",
        "surface-container-high": "#eae8e5",
        "inverse-on-surface": "#f2f0ed",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Work Sans", "sans-serif"],
        display: ["Inter", "sans-serif"],
      },
      spacing: {
        xl: "120px",
        lg: "48px",
        md: "24px",
        sm: "12px",
        xs: "4px",
      },
      keyframes: {
        pulseGreen: {
          "0%": { boxShadow: "0 0 0 0 rgba(76, 175, 125, 0.4)" },
          "70%": { boxShadow: "0 0 0 10px rgba(76, 175, 125, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(76, 175, 125, 0)" },
        },
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideRight: {
          "0%": { opacity: "0", transform: "translateX(-40px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-1000px 0" },
          "100%": { backgroundPosition: "1000px 0" },
        },
        floatY: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
      },
      animation: {
        pulseGreen: "pulseGreen 2s infinite",
        fadeUp: "fadeUp 0.8s ease forwards",
        fadeIn: "fadeIn 1s ease forwards",
        slideRight: "slideRight 0.8s ease forwards",
        scaleIn: "scaleIn 0.6s ease forwards",
        floatY: "floatY 4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
export default config;